# Site settings
title: Crazzle - Blog
email: ---
description: "Stuff about technology, software and ideas."
baseurl: ""
url: ""

# Build settings
markdown: redcarpet
permalink: pretty
highlighter: pygments
